version: '3.8'

services:
    postgres:
        container_name: postgres_db
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data

    webapi:
        container_name: api
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5001:8080"
        depends_on:
            - postgres
        volumes:
            - /volumes/api/images/products:/app/data/images/products
            - /volumes/api/images/containers:/app/data/images/containers

volumes:
    postgres_data: