version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - ConnectionStrings__Default=Host=dpg-cv06cf2n91rc73fl46s0-a.oregon-postgres.render.com;Port=5432;Database=db_wywu;Username=userdb;Password=jRNIf4uGBatrNlniu2leBsAEmA7b05Yb;
      - ASPNETCORE_ENVIRONMENT=Production
      - GoogleAuthSettings__ClientId=219955824362-0rhvb42q1827djp1m7ao56921c6ivn9o.apps.googleusercontent.com
      - AuthSettings__key=sItTJw6q2Pc7uFScU3JLrUF4S3S6krpgGhZeT9ZyWd2HA5vDNcyPLvo7BSGTeFYQ
      - AuthSettings__issuer=oa.edu.ua
      - AuthSettings__audience=oa.edu.ua
    ports:
      - "8080:8080"
    networks:
      - finalback_network

networks:
  finalback_network: